version: "3.8"
services:
  db:
    image: postgres
    container_name: postgresDB
    restart: always
    ports:
      - ${DB_PORT}:${DB_PORT}
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_DATABASE}

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    links:
      - db
    working_dir: /usr/src/newServer
    restart: always
    env_file:
      - .env

    volumes:
      - ./:/usr/src/newServer
    ports:
      - ${IGNITE_API_PORT}:${PORT}
